import enum
from sqlalchemy import Column, Integer, String, DateTime, Enum, ForeignKey
from sqlalchemy.orm import relationship
from app.models.user import Base


class EntryStatus(str, enum.Enum):
    WAITING = "WAITING"    # joined, waiting in line
    AT_BAR = "AT_BAR"      # called to the physical bar
    SERVED = "SERVED"      # completed / order taken
    LEFT = "LEFT"          # abandoned before being served


class QueueEntry(Base):
    __tablename__ = "queue_entry"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("queue_session.id", ondelete="CASCADE"), nullable=False, index=True)
    queue_id = Column(Integer, ForeignKey("queue.id"), nullable=False, index=True)

    # Sequential position within the day-session (1, 2, 3 … never resets mid-day)
    position = Column(Integer, nullable=False)

    # Anonymous device token generated by the customer's browser (UUID stored in localStorage).
    # Not linked to any personal data — purely behavioural fingerprint.
    # Hashed with SHA-256 before storage so the raw token never persists server-side.
    customer_token = Column(String(64), nullable=True, index=True)

    status = Column(Enum(EntryStatus), nullable=False, default=EntryStatus.WAITING)

    joined_at = Column(DateTime(timezone=True), nullable=False)
    called_at = Column(DateTime(timezone=True), nullable=True)   # moved to AT_BAR
    served_at = Column(DateTime(timezone=True), nullable=True)   # marked SERVED
    left_at = Column(DateTime(timezone=True), nullable=True)     # marked LEFT

    session = relationship("QueueSession", back_populates="entries")
